<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "mailsignature"
 *
 * Auto generated by Extension Builder 2015-12-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Mail Signature Service',
	'description' => 'Offers Classes for better Emails: Add a standard Signature for different Languages, Hook to fe User Password Forgotten and more ',
	'category' => 'misc',
	'author' => 'Jörg Velletti',
	'author_email' => 'typo3@velletti.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);